/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommandeFournisseurResponse } from '../../models/commande-fournisseur-response';

export interface FindByCode$Params {
  code: string;
}

export function findByCode(http: HttpClient, rootUrl: string, params: FindByCode$Params, context?: HttpContext): Observable<StrictHttpResponse<CommandeFournisseurResponse>> {
  const rb = new RequestBuilder(rootUrl, findByCode.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommandeFournisseurResponse>;
    })
  );
}

findByCode.PATH = '/commandes-fournisseur/code/{code}';
