/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArticleResponse } from '../../models/article-response';

export interface FindByCode2$Params {
  code: string;
}

export function findByCode2(http: HttpClient, rootUrl: string, params: FindByCode2$Params, context?: HttpContext): Observable<StrictHttpResponse<ArticleResponse>> {
  const rb = new RequestBuilder(rootUrl, findByCode2.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArticleResponse>;
    })
  );
}

findByCode2.PATH = '/articles/filtre/code/{code}';
