/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseArticleResponse } from '../../models/page-response-article-response';

export interface FindByCategorieId$Params {
  page?: number;
  size?: number;
  id: number;
}

export function findByCategorieId(http: HttpClient, rootUrl: string, params: FindByCategorieId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseArticleResponse>> {
  const rb = new RequestBuilder(rootUrl, findByCategorieId.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseArticleResponse>;
    })
  );
}

findByCategorieId.PATH = '/articles/filtre/categorie/{id}';
