/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategorieResponse } from '../../models/categorie-response';

export interface FindById7$Params {
  code: string;
}

export function findById7(http: HttpClient, rootUrl: string, params: FindById7$Params, context?: HttpContext): Observable<StrictHttpResponse<CategorieResponse>> {
  const rb = new RequestBuilder(rootUrl, findById7.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategorieResponse>;
    })
  );
}

findById7.PATH = '/categories/code/{code}';
