/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategorieResponse } from '../models/categorie-response';
export interface ArticleResponse {
  categorie?: CategorieResponse;
  code?: string;
  designation?: string;
  id?: number;
  photo?: string;
  prixUnitaireHt?: number;
  prixUnitaireTtc?: number;
  tauxTva?: number;
}
