/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneCommandeClientRequest } from '../models/ligne-commande-client-request';
export interface CommandeClientRequest {
  client: number;
  code: string;
  dateCommande: string;
  etatCommande: 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
  ligneCommandeClients: Array<LigneCommandeClientRequest>;
}
