/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FournisseurResponse {
  commandeFournisseurs?: Array<number>;
  email?: string;
  id?: number;
  nom?: string;
  numeroCNI?: string;
  numeroTel?: string;
  sexe?: 'MASCULIN' | 'FEMININ';
}
