/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleResponse } from '../models/article-response';
import { CommandeFournisseurResponse } from '../models/commande-fournisseur-response';
export interface LigneCommandeFournisseurResponse {
  article?: ArticleResponse;
  commandeFournisseur?: CommandeFournisseurResponse;
  id?: number;
  prixUnitaire?: number;
  quantite?: number;
}
