/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleResponse } from '../models/article-response';
import { CommandeClientResponse } from '../models/commande-client-response';
export interface LigneCommandeClientResponse {
  article?: ArticleResponse;
  commandeClient?: CommandeClientResponse;
  id?: number;
  prixUnitaire?: number;
  quantite?: number;
}
