/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LigneCommandeFournisseurRequest {
  article: number;
  commandeFournisseur: number;
  prixUnitaire: number;
  quantite: number;
}
