/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneVenteRequest } from '../models/ligne-vente-request';
export interface VenteRequest {
  code: string;
  dateVente: string;
  ligneVentes: Array<LigneVenteRequest>;
}
