/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientResponse } from '../../models/client-response';

export interface FindByNumeroCni1$Params {
  'client-numero-cni': string;
}

export function findByNumeroCni1(http: HttpClient, rootUrl: string, params: FindByNumeroCni1$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientResponse>> {
  const rb = new RequestBuilder(rootUrl, findByNumeroCni1.PATH, 'get');
  if (params) {
    rb.path('client-numero-cni', params['client-numero-cni'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientResponse>;
    })
  );
}

findByNumeroCni1.PATH = '/clients/numero-cni/{client-numero-cni}';
