/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UtilisateurResponse } from '../../models/utilisateur-response';

export interface FindByLogin$Params {
  login: string;
}

export function findByLogin(http: HttpClient, rootUrl: string, params: FindByLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<UtilisateurResponse>> {
  const rb = new RequestBuilder(rootUrl, findByLogin.PATH, 'get');
  if (params) {
    rb.path('login', params.login, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UtilisateurResponse>;
    })
  );
}

findByLogin.PATH = '/utilisateurs/login/{login}';
