/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategorieResponse } from './categorie-response';


export interface ArticleResponse { 
    id?: number;
    code?: string;
    designation?: string;
    prixUnitaireHt?: number;
    tauxTva?: number;
    prixUnitaireTtc?: number;
    categorie?: CategorieResponse;
    photo?: string;
}

