/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UtilisateurResponse } from './utilisateur-response';


export interface AuthenticationResponse { 
    utilisateur?: UtilisateurResponse;
    token?: string;
}

