/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeFournisseurRequest } from './ligne-commande-fournisseur-request';


export interface CommandeFournisseurRequest { 
    id?: number;
    code: string;
    dateCommande: string;
    etatCommande: CommandeFournisseurRequest.EtatCommandeEnum;
    fournisseur: number;
    ligneCommandeFournisseurs: Array<LigneCommandeFournisseurRequest>;
}
export namespace CommandeFournisseurRequest {
    export type EtatCommandeEnum = 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
    export const EtatCommandeEnum = {
        EnPreparation: 'EN_PREPARATION' as EtatCommandeEnum,
        Validee: 'VALIDEE' as EtatCommandeEnum,
        Livree: 'LIVREE' as EtatCommandeEnum
    };
}


