/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeClientRequest } from './ligne-commande-client-request';


export interface CommandeClientRequest { 
    id?: number;
    code: string;
    dateCommande: string;
    client: number;
    ligneCommandeClients: Array<LigneCommandeClientRequest>;
}

