/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeClientRequest } from './ligne-commande-client-request';


export interface CommandeClientRequest { 
    id?: number;
    code: string;
    dateCommande: string;
    etatCommande: CommandeClientRequest.EtatCommandeEnum;
    client: number;
    ligneCommandeClients: Array<LigneCommandeClientRequest>;
}
export namespace CommandeClientRequest {
    export type EtatCommandeEnum = 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
    export const EtatCommandeEnum = {
        EnPreparation: 'EN_PREPARATION' as EtatCommandeEnum,
        Validee: 'VALIDEE' as EtatCommandeEnum,
        Livree: 'LIVREE' as EtatCommandeEnum
    };
}


