/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeFournisseurResponse } from './ligne-commande-fournisseur-response';
import { FournisseurResponse } from './fournisseur-response';


export interface CommandeFournisseurResponse { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseurResponse.EtatCommandeEnum;
    fournisseur?: FournisseurResponse;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseurResponse>;
}
export namespace CommandeFournisseurResponse {
    export type EtatCommandeEnum = 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
    export const EtatCommandeEnum = {
        EnPreparation: 'EN_PREPARATION' as EtatCommandeEnum,
        Validee: 'VALIDEE' as EtatCommandeEnum,
        Livree: 'LIVREE' as EtatCommandeEnum
    };
}


