/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleResponse } from './article-response';


export interface LigneCommandeFournisseurResponse { 
    id?: number;
    article?: ArticleResponse;
    quantite?: number;
    prixUnitaire?: number;
}

