/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MouvementStockRequest { 
    id?: number;
    dateMouvement: string;
    typeMouvement: MouvementStockRequest.TypeMouvementEnum;
    provenance: MouvementStockRequest.ProvenanceEnum;
    quantite: number;
    article: number;
}
export namespace MouvementStockRequest {
    export type TypeMouvementEnum = 'ENTREE' | 'SORTIE' | 'CORRECTION_POS' | 'CORRECTION_NEG';
    export const TypeMouvementEnum = {
        Entree: 'ENTREE' as TypeMouvementEnum,
        Sortie: 'SORTIE' as TypeMouvementEnum,
        CorrectionPos: 'CORRECTION_POS' as TypeMouvementEnum,
        CorrectionNeg: 'CORRECTION_NEG' as TypeMouvementEnum
    };
    export type ProvenanceEnum = 'COMMANDE_CLIENT' | 'COMMANDE_FOURNISSEUR' | 'CORRECTION' | 'VENTE';
    export const ProvenanceEnum = {
        CommandeClient: 'COMMANDE_CLIENT' as ProvenanceEnum,
        CommandeFournisseur: 'COMMANDE_FOURNISSEUR' as ProvenanceEnum,
        Correction: 'CORRECTION' as ProvenanceEnum,
        Vente: 'VENTE' as ProvenanceEnum
    };
}


