/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVenteRequest } from './ligne-vente-request';


export interface VenteRequest { 
    id?: number;
    code: string;
    dateVente: string;
    ligneVentes: Array<LigneVenteRequest>;
}

