/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommandeClientResponse } from '../../models/commande-client-response';

export interface FindByCode1$Params {
  code: string;
}

export function findByCode1(http: HttpClient, rootUrl: string, params: FindByCode1$Params, context?: HttpContext): Observable<StrictHttpResponse<CommandeClientResponse>> {
  const rb = new RequestBuilder(rootUrl, findByCode1.PATH, 'get');
  if (params) {
    rb.path('code', params.code, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommandeClientResponse>;
    })
  );
}

findByCode1.PATH = '/commandes-client/code/{code}';
