/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { VenteService } from './services/vente.service';
import { UtilisateurService } from './services/utilisateur.service';
import { RoleService } from './services/role.service';
import { MouvementStockService } from './services/mouvement-stock.service';
import { FournisseurService } from './services/fournisseur.service';
import { CommandeFournisseurService } from './services/commande-fournisseur.service';
import { CommandeClientService } from './services/commande-client.service';
import { ClientService } from './services/client.service';
import { CategorieService } from './services/categorie.service';
import { AuthenticationService } from './services/authentication.service';
import { ArticleService } from './services/article.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    VenteService,
    UtilisateurService,
    RoleService,
    MouvementStockService,
    FournisseurService,
    CommandeFournisseurService,
    CommandeClientService,
    ClientService,
    CategorieService,
    AuthenticationService,
    ArticleService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
