/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FournisseurResponse } from '../../models/fournisseur-response';

export interface FindByNumeroTel$Params {
  'numero-tel': string;
}

export function findByNumeroTel(http: HttpClient, rootUrl: string, params: FindByNumeroTel$Params, context?: HttpContext): Observable<StrictHttpResponse<FournisseurResponse>> {
  const rb = new RequestBuilder(rootUrl, findByNumeroTel.PATH, 'get');
  if (params) {
    rb.path('numero-tel', params['numero-tel'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FournisseurResponse>;
    })
  );
}

findByNumeroTel.PATH = '/fournisseurs/numero-tel/{numero-tel}';
