/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleRequest {
  categorie: number;
  code: string;
  designation: string;
  prixUnitaireHt: number;
  tauxTva: number;
}
