/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategorieResponse {
  code?: string;
  designation?: string;
  id?: number;
  totalArticles?: number;
}
