/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangeArticleCommandeRequest {
  articleId: number;
  commandeId: number;
  ligneCommandeId: number;
}
