/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangeEtatCommandeRequest {
  commandeId: number;
  etatCommande: 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
}
