/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangeQuantiteCommandeRequest {
  commandeId: number;
  ligneCommandeId: number;
  quantite: number;
}
