/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FournisseurResponse } from '../models/fournisseur-response';
export interface CommandeFournisseurResponse {
  code?: string;
  dateCommande?: string;
  etatCommande?: 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
  fournisseur?: FournisseurResponse;
  id?: number;
}
