/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FournisseurRequest {
  email?: string;
  nom: string;
  numeroCNI?: string;
  numeroTel: string;
  sexe?: 'MASCULIN' | 'FEMININ';
}
