/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleResponse } from '../models/article-response';
import { VenteResponse } from '../models/vente-response';
export interface LigneVenteResponse {
  article?: ArticleResponse;
  id?: number;
  prixUnitaire?: number;
  quantite?: number;
  vente?: VenteResponse;
}
