/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LigneVenteRequest {
  article: number;
  prixUnitaire: number;
  quantite: number;
  vente: number;
}
