/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MouvementStockResponse {
  article?: number;
  dateMouvement?: string;
  id?: number;
  quantite?: number;
  typeMouvement?: 'ENTREE' | 'SORTIE' | 'CORRECTION_POS' | 'CORRECTION_NEG';
}
