/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneCommandeFournisseurResponse } from '../models/ligne-commande-fournisseur-response';
export interface PageResponseLigneCommandeFournisseurResponse {
  content?: Array<LigneCommandeFournisseurResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
}
