/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneCommandeClientResponse } from '../models/ligne-commande-client-response';
export interface PageResponseLigneCommandeClientResponse {
  content?: Array<LigneCommandeClientResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
