/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MouvementStockResponse } from '../models/mouvement-stock-response';
export interface PageResponseMouvementStockResponse {
  content?: Array<MouvementStockResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
