/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommandeClientResponse } from '../models/commande-client-response';
export interface PageResponseCommandeClientResponse {
  content?: Array<CommandeClientResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
