/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UtilisateurResponse } from '../models/utilisateur-response';
export interface PageResponseUtilisateurResponse {
  content?: Array<UtilisateurResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
}
