/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommandeFournisseurResponse } from '../models/commande-fournisseur-response';
export interface PageResponseCommandeFournisseurResponse {
  content?: Array<CommandeFournisseurResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
}
