/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FournisseurResponse } from '../models/fournisseur-response';
export interface PageResponseFournisseurResponse {
  content?: Array<FournisseurResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
}
