/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LigneVenteResponse } from '../models/ligne-vente-response';
export interface PageResponseLigneVenteResponse {
  content?: Array<LigneVenteResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
