/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UtilisateurResponse {
  id?: number;
  login?: string;
  nom?: string;
  photo?: string;
  sexe?: 'MASCULIN' | 'FEMININ';
}
