export * from './article.service';
import { ArticleService } from './article.service';
export * from './article.serviceInterface';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './categorie.service';
import { CategorieService } from './categorie.service';
export * from './categorie.serviceInterface';
export * from './client.service';
import { ClientService } from './client.service';
export * from './client.serviceInterface';
export * from './commande-client.service';
import { CommandeClientService } from './commande-client.service';
export * from './commande-client.serviceInterface';
export * from './commande-fournisseur.service';
import { CommandeFournisseurService } from './commande-fournisseur.service';
export * from './commande-fournisseur.serviceInterface';
export * from './fournisseur.service';
import { FournisseurService } from './fournisseur.service';
export * from './fournisseur.serviceInterface';
export * from './mouvement-stock.service';
import { MouvementStockService } from './mouvement-stock.service';
export * from './mouvement-stock.serviceInterface';
export * from './role.service';
import { RoleService } from './role.service';
export * from './role.serviceInterface';
export * from './utilisateur.service';
import { UtilisateurService } from './utilisateur.service';
export * from './utilisateur.serviceInterface';
export * from './vente.service';
import { VenteService } from './vente.service';
export * from './vente.serviceInterface';
export const APIS = [ArticleService, AuthenticationService, CategorieService, ClientService, CommandeClientService, CommandeFournisseurService, FournisseurService, MouvementStockService, RoleService, UtilisateurService, VenteService];
