/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ArticleRequest } from '../model/models';
import { ArticleResponse } from '../model/models';
import { PageResponseArticleResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ArticleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    deleteArticle(id: number, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    findAllArticles(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseArticleResponse>;

    /**
     * 
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    findAllArticlesByCategorieId(id: number, page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseArticleResponse>;

    /**
     * 
     * 
     */
    findAllArticlesList(extraHttpRequestParams?: any): Observable<Array<ArticleResponse>>;

    /**
     * 
     * 
     * @param code 
     */
    findArticleByCode(code: string, extraHttpRequestParams?: any): Observable<ArticleResponse>;

    /**
     * 
     * 
     * @param id 
     */
    findArticleById(id: number, extraHttpRequestParams?: any): Observable<ArticleResponse>;

    /**
     * 
     * 
     * @param articleRequest 
     */
    saveArticle(articleRequest: ArticleRequest, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param id 
     * @param file 
     */
    uploadArticlePhoto(id: number, file: Blob, extraHttpRequestParams?: any): Observable<object>;

}
