/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ClientRequest } from '../model/models';
import { ClientResponse } from '../model/models';
import { PageResponseClientResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClientServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    deleteClient(id: number, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    findAllClients(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseClientResponse>;

    /**
     * 
     * 
     */
    findAllClientsList(extraHttpRequestParams?: any): Observable<Array<ClientResponse>>;

    /**
     * 
     * 
     * @param clientEmail 
     */
    findClientByEmail(clientEmail: string, extraHttpRequestParams?: any): Observable<ClientResponse>;

    /**
     * 
     * 
     * @param clientId 
     */
    findClientById(clientId: number, extraHttpRequestParams?: any): Observable<ClientResponse>;

    /**
     * 
     * 
     * @param clientNumeroCni 
     */
    findClientByNumeroCNI(clientNumeroCni: string, extraHttpRequestParams?: any): Observable<ClientResponse>;

    /**
     * 
     * 
     * @param clientNumeroTel 
     */
    findClientByNumeroTel(clientNumeroTel: string, extraHttpRequestParams?: any): Observable<ClientResponse>;

    /**
     * 
     * 
     * @param clientRequest 
     */
    saveClient(clientRequest: ClientRequest, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param id 
     * @param file 
     */
    uploadClientPhoto(id: number, file: Blob, extraHttpRequestParams?: any): Observable<object>;

}
