/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FournisseurRequest } from '../model/models';
import { FournisseurResponse } from '../model/models';
import { PageResponseFournisseurResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FournisseurServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    deleteFournisseur(id: number, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    findAllFournisseurs(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseFournisseurResponse>;

    /**
     * 
     * 
     */
    findAllFournisseursList(extraHttpRequestParams?: any): Observable<Array<FournisseurResponse>>;

    /**
     * 
     * 
     * @param email 
     */
    findFournisseurByEmail(email: string, extraHttpRequestParams?: any): Observable<FournisseurResponse>;

    /**
     * 
     * 
     * @param id 
     */
    findFournisseurById(id: number, extraHttpRequestParams?: any): Observable<FournisseurResponse>;

    /**
     * 
     * 
     * @param numeroCni 
     */
    findFournisseurByNumeroCNI(numeroCni: string, extraHttpRequestParams?: any): Observable<FournisseurResponse>;

    /**
     * 
     * 
     * @param numeroTel 
     */
    findFournisseurByNumeroTel(numeroTel: string, extraHttpRequestParams?: any): Observable<FournisseurResponse>;

    /**
     * 
     * 
     * @param fournisseurRequest 
     */
    saveFournisseur(fournisseurRequest: FournisseurRequest, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param id 
     * @param file 
     */
    uploadFournisseurPhoto(id: number, file: Blob, extraHttpRequestParams?: any): Observable<object>;

}
