/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MouvementStockRequest } from '../model/models';
import { MouvementStockResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MouvementStockServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    findAllMouvementStocks(extraHttpRequestParams?: any): Observable<Array<MouvementStockResponse>>;

    /**
     * 
     * 
     * @param id 
     */
    findMouvementStockById(id: number, extraHttpRequestParams?: any): Observable<MouvementStockResponse>;

    /**
     * 
     * 
     * @param mouvementStockRequest 
     */
    saveMouvementStock(mouvementStockRequest: MouvementStockRequest, extraHttpRequestParams?: any): Observable<number>;

}
