/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PageResponseLigneVenteResponse } from '../model/models';
import { PageResponseVenteResponse } from '../model/models';
import { VenteRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VenteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    findAllLigneVentes(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseLigneVenteResponse>;

    /**
     * 
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    findAllLigneVentesByArticle(id: number, page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseLigneVenteResponse>;

    /**
     * 
     * 
     * @param id 
     * @param page 
     * @param size 
     */
    findAllLigneVentesByVente(id: number, page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseLigneVenteResponse>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    findAllVentes(page?: number, size?: number, extraHttpRequestParams?: any): Observable<PageResponseVenteResponse>;

    /**
     * 
     * 
     * @param venteRequest 
     */
    saveVente(venteRequest: VenteRequest, extraHttpRequestParams?: any): Observable<number>;

}
