/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseMouvementStockResponse } from '../../models/page-response-mouvement-stock-response';

export interface FindAllByArticle$Params {
  page?: number;
  size?: number;
  id: number;
}

export function findAllByArticle(http: HttpClient, rootUrl: string, params: FindAllByArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMouvementStockResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllByArticle.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseMouvementStockResponse>;
    })
  );
}

findAllByArticle.PATH = '/mouvements-stock/article/{id}';
