/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { VenteService } from './services/vente.service';
export { UtilisateurService } from './services/utilisateur.service';
export { RoleService } from './services/role.service';
export { MouvementStockService } from './services/mouvement-stock.service';
export { FournisseurService } from './services/fournisseur.service';
export { CommandeFournisseurService } from './services/commande-fournisseur.service';
export { CommandeClientService } from './services/commande-client.service';
export { ClientService } from './services/client.service';
export { CategorieService } from './services/categorie.service';
export { AuthenticationService } from './services/authentication.service';
export { ArticleService } from './services/article.service';
